// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_VR44IbF8DSbtHbAbGm3PeOvV3Gf4u60',
    appId: '1:632929787357:web:a2a0544dd2b75d2407aa34',
    messagingSenderId: '632929787357',
    projectId: 'oontz-73c57',
    authDomain: 'oontz-73c57.firebaseapp.com',
    storageBucket: 'oontz-73c57.appspot.com',
    measurementId: 'G-GJ74SLLE5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO_RUQMt9PqS5jjfa_MdY-DOLTR89O1qI',
    appId: '1:632929787357:android:60721e6c699a2c4807aa34',
    messagingSenderId: '632929787357',
    projectId: 'oontz-73c57',
    storageBucket: 'oontz-73c57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDBuhaNa0N5Qf5RWQSzpiYdVEf8exPnVE',
    appId: '1:632929787357:ios:072206def5faa17307aa34',
    messagingSenderId: '632929787357',
    projectId: 'oontz-73c57',
    storageBucket: 'oontz-73c57.appspot.com',
    iosBundleId: 'com.example.oontz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDBuhaNa0N5Qf5RWQSzpiYdVEf8exPnVE',
    appId: '1:632929787357:ios:072206def5faa17307aa34',
    messagingSenderId: '632929787357',
    projectId: 'oontz-73c57',
    storageBucket: 'oontz-73c57.appspot.com',
    iosBundleId: 'com.example.oontz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_VR44IbF8DSbtHbAbGm3PeOvV3Gf4u60',
    appId: '1:632929787357:web:f5ab3540a5fe8bc007aa34',
    messagingSenderId: '632929787357',
    projectId: 'oontz-73c57',
    authDomain: 'oontz-73c57.firebaseapp.com',
    storageBucket: 'oontz-73c57.appspot.com',
    measurementId: 'G-5C6TGDJQK9',
  );
}
