name: oontz
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.20.0
  cloud_firestore: ^4.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The Flutter Driver for integration testing
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true

  # Uncomment if you have assets
  # assets:
  #   - assets/